### ISSUE TITLE
Sprite `frameheight` documentation inconsistencies

### ISSUE THREAD

**Issue by kenherbert** [melonjs/tutorial-platformer#37] opened 2020-05-04 17:11 UTC
The tutorial says to not define `frameheight` on the sprite, but when I don't the scene fails to load with `Uncaught TypeError: Cannot read property 'offset' of undefined`.

If I define `frameheight` as an empty value the scene loads, but the sprite doesn't show. If I define `frameheight` with a correct value, the scene loads and the sprite is visible.

**Comment by obiot** [comment] 2020-07-14 09:29
which version of melonJS are you using ? I just tested with both 7.x and the 8.x dev branch and both works without specifying frameheight, I also tried by removing the frameheight definition/allocation on part 5 for the enemy and same it took the default image height size instead as expected.

pretty sure it should working with 6.x but sure I can be wrong, closing this one anyway since I could not reproduce it on my side with 7.x and onward.

**Closed as completed by obiot** 2020-07-14 09:29 UTC
